[pytest]
python_files = test*.py
python_functions = test_*

[flake8]
extend-ignore =
;   E402 refers to imports only being at the top of a file
;   so I ignore this error, because firstly I need to add another directory using sys
    E402,

;   F401: A module has been imported but is not used anywhere in the file
;   caused by no direct calling in calculate.py, only eval in calc
    F401,

;   W191: indentation contains tabs
;   it would take infinite time to change all of the tabs to spaces
    W191
